---
slurm_packages:
  - slurmd
  - libpmi
  - strace

slurm_role: compute

mpi_packages:
  oracle:
    - mpich
    - openmpi
    - hdf5-static
    - hdf5-mpich-static
    - hdf5-openmpi-static
    - libpng-devel
    - pugixml-devel
    - fmt-devel
    - xtensor-devel
    - pmix-devel
    - pmix pmix-tools
  google:
    - mpich
    - openmpi
    - hdf5-static
    - hdf5-mpich-static
    - hdf5-openmpi-static
    - libpng-devel
    - pugixml-devel
    - fmt-devel
    - xtensor-devel
    - pmix-devel
    - pmix pmix-tools
  aws:
    - mpich
    - openmpi
    - hdf5-static
    - hdf5-mpich-static
    - hdf5-openmpi-static
    - libpng-devel
    - pugixml-devel
    - fmt-devel
    - xtensor-devel
    - pmix-devel
    - pmix
    - pmix-tools

monitoring_role: client

ldap_hostname: "{{ ansible_local.citc.ldap_hostname }}"
