---

slurm_accounting_db_password: "{{ lookup('ansible.builtin.password', '/tmp/slurmpasswordfile', chars=['ascii_letters', 'digits', 'hexdigits']) }}"

slurm_packages:
  - slurmctld
  - slurmdbd
  - libpmi
  - strace

slurm_role: mgmt

slurm_elastic:
  oracle:
    config_directory: /home/slurm/.oci/

install_packages:
  - xorg-x11-xauth
  - python3-devel
  - python3.11-devel
  - "@Development Tools"
  - vim-enhanced

mpi_packages:
  oracle: []
  google: []
  aws:
    - openmpi-devel
    - mpich-devel
    - hwloc-devel
    - hdf5-static
    - hdf5-mpich-static
    - hdf5-openmpi-static
    - libpng-devel
    - pugixml-devel
    - fmt-devel
    - xtensor-devel
    - pmix-devel
    - pmix-tools

monitoring_role: master

ldap_dm_password: "{{ lookup('ansible.builtin.password', '/etc/citc/ldapdmpasswordfile', chars=['ascii_letters', 'digits']) }}"

ldap_hostname: "{{ ansible_nodename }}"
